import { NextResponse } from "next/server";
import { Types } from "mongoose";
import { requireApiGymAdmin } from "@/lib/auth/api-guard";
import { getReceiptData } from "@/lib/data/payments";
import { PaymentModel } from "@/models/payment.model";
import { tenant } from "@/lib/data/tenant";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function pdfText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
function money(value: number): string {
  return `Rs. ${Math.round(value).toLocaleString("en-IN")}`;
}
function date(value: Date | null): string {
  return value
    ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(value)
    : "—";
}

function buildPdf(data: NonNullable<Awaited<ReturnType<typeof getReceiptData>>>): Uint8Array {
  const c: string[] = [];
  const t = (v: string, x: number, y: number, s = 11, b = false) =>
    c.push(`BT /${b ? "F2" : "F1"} ${s} Tf ${x} ${y} Td (${pdfText(v)}) Tj ET`);
  c.push("0.5 w", "50 50 495 742 re S");
  t(data.gym.name || "Fitaah", 70, 735, 22, true);
  t("PAYMENT RECEIPT", 70, 708, 13, true);
  t(`Receipt No: ${data.receiptNumber}`, 365, 735, 10);
  t(`Payment Date: ${date(data.paymentDate)}`, 365, 718, 10);
  c.push("70 695 m 525 695 l S");
  t("MEMBER DETAILS", 70, 670, 10, true);
  t(`Name: ${data.member.name}`, 70, 650);
  t(`Mobile: ${data.member.phone || "—"}`, 70, 632);
  t(`Plan: ${data.planName}`, 70, 614);
  t(`Membership: ${date(data.startDate)} - ${date(data.endDate)}`, 70, 596);
  c.push("70 575 m 525 575 l S");
  t("PAYMENT DETAILS", 70, 550, 10, true);
  t("Membership Amount", 70, 525); t(money(data.membershipAmount), 400, 525, 11, true);
  t("Amount Paid", 70, 500); t(money(data.amountPaid), 400, 500, 11, true);
  t("Payment Method", 70, 475); t(data.method.replaceAll("_", " "), 400, 475, 11, true);
  t("Total Paid", 70, 450); t(money(data.totalPaid), 400, 450, 11, true);
  t("Outstanding", 70, 425); t(money(data.outstanding), 400, 425, 11, true);
  if (data.transactionReference) { t("Transaction Reference", 70, 400); t(data.transactionReference, 250, 400, 10); }
  c.push("70 370 m 525 370 l S");
  t(data.gym.address || "", 70, 345, 9);
  t(`Phone: ${data.gym.phone || "—"}`, 70, 328, 9);
  t(`Email: ${data.gym.email || "—"}`, 70, 311, 9);
  t("Thank you for your payment.", 70, 265, 12, true);
  t("Please keep this receipt for your records.", 70, 245, 9);
  t("Generated by Fitaah", 70, 75, 8);
  const stream = c.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (let i = 0; i < objects.length; i += 1) {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i += 1) pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new TextEncoder().encode(pdf);
}

export async function GET(_request: Request, { params }: { params: { id: string } }) {
  const auth = await requireApiGymAdmin();
  if (!auth.ok) return auth.response;
  if (!Types.ObjectId.isValid(params.id)) return NextResponse.json({ error: "Invalid membership" }, { status: 400 });

  const payment = await PaymentModel.findOne(
    tenant(auth.user.gymId as string).filter({ membershipId: params.id }),
  ).sort({ paymentDate: -1, createdAt: -1 }).lean();
  if (!payment) return NextResponse.json({ error: "No payment found for this membership" }, { status: 404 });

  const data = await getReceiptData(auth.user.gymId as string, payment._id.toString());
  if (!data) return NextResponse.json({ error: "Payment not found" }, { status: 404 });

  return new NextResponse(buildPdf(data) as BodyInit, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${data.receiptNumber}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
