import Link from "next/link";
import { ArrowLeft, CalendarDays, Edit3, Mail, MapPin, Phone, ShieldAlert, UserRound, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireGymContext } from "@/lib/auth/guards";
import { getMemberById } from "@/lib/data/members";
import type { MemberStatus } from "@/lib/constants";

export const dynamic = "force-dynamic";
type PageProps = { params: Promise<{ id: string }> };
function statusClass(status: MemberStatus): string { if (status === "ACTIVE") return "border-emerald-200 bg-emerald-50 text-emerald-700"; if (status === "FROZEN") return "border-amber-200 bg-amber-50 text-amber-700"; return "border-slate-200 bg-slate-50 text-slate-600"; }
function formatDate(value: string | null): string { if (!value) return "—"; return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }

export default async function MemberDetailsPage({ params }: PageProps) {
  const { gym } = await requireGymContext(); const { id } = await params; const member = await getMemberById(gym.id, id); if (!member) notFound();
  const initials = member.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <div className="mx-auto max-w-6xl space-y-5 sm:space-y-7">
    <div className="flex items-center gap-3"><Link href="/members" className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-500 shadow-sm transition hover:border-emerald-200 hover:text-emerald-600"><ArrowLeft className="h-4 w-4" /></Link><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-600">Member profile</p><h1 className="mt-1 truncate font-heading text-2xl font-black tracking-tight text-slate-900 sm:text-3xl">{member.name}</h1></div><Button asChild variant="outline" className="ml-auto h-10 rounded-xl border-slate-200 bg-white"><Link href={`/members/${member.id}/edit`}><Edit3 className="mr-1.5 h-4 w-4 text-blue-500" />Edit profile</Link></Button></div>
    <section className="relative overflow-hidden rounded-[1.75rem] border border-emerald-100 bg-gradient-to-br from-white via-emerald-50/70 to-cyan-50/70 p-5 shadow-[0_18px_50px_rgba(16,185,129,0.08)] sm:p-7 lg:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-emerald-300/20 blur-3xl" /><div className="absolute bottom-0 right-1/3 h-40 w-40 rounded-full bg-cyan-300/15 blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-[1.5rem] bg-gradient-to-br from-emerald-500 to-teal-500 text-2xl font-black text-white shadow-xl shadow-emerald-500/20">{initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-heading text-2xl font-black text-slate-900">{member.name}</h2><Badge variant="outline" className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusClass(member.status)}`}>{member.status}</Badge></div><p className="mt-1.5 text-sm text-slate-500">Member since {formatDate(member.joiningDate)} · {member.phone}</p></div><div className="rounded-2xl border border-white/80 bg-white/70 px-5 py-3 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Membership</p><p className="mt-1 font-bold text-slate-800">{member.membership?.plan ?? "Not assigned"}</p></div></div></section>
    <div className="grid gap-5 lg:grid-cols-[1.3fr_0.7fr]">
      <section className="rounded-[1.5rem] border border-slate-200/80 bg-white p-5 shadow-[0_10px_35px_rgba(15,23,42,0.04)] sm:p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><UserRound className="h-4 w-4" /></span><div><h2 className="font-heading text-base font-bold text-slate-800">Personal information</h2><p className="text-xs text-slate-400">Everything you need to know about this member.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Phone</p><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-slate-700"><Phone className="h-4 w-4 text-emerald-500" />{member.phone}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Email</p><p className="mt-2 flex items-center gap-2 truncate text-sm font-semibold text-slate-700"><Mail className="h-4 w-4 text-blue-500" />{member.email || "Not provided"}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Gender</p><p className="mt-2 text-sm font-semibold capitalize text-slate-700">{member.gender.toLowerCase()}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Date of birth</p><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-slate-700"><CalendarDays className="h-4 w-4 text-violet-500" />{formatDate(member.dateOfBirth)}</p></div><div className="sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Address</p><p className="mt-2 flex items-start gap-2 text-sm font-semibold text-slate-700"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-rose-500" />{member.address || "Not provided"}</p></div><div className="sm:col-span-2"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Emergency contact</p><p className="mt-2 text-sm font-semibold text-slate-700">{member.emergencyContact || "Not provided"}</p></div></div></section>
      <section className="rounded-[1.5rem] border border-slate-200/80 bg-white p-5 shadow-[0_10px_35px_rgba(15,23,42,0.04)] sm:p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-50 text-cyan-600"><Users className="h-4 w-4" /></span><div><h2 className="font-heading text-base font-bold text-slate-800">Membership</h2><p className="text-xs text-slate-400">Latest plan and billing snapshot.</p></div></div>{member.membership ? <div className="rounded-2xl border border-emerald-100 bg-gradient-to-br from-emerald-50/80 to-cyan-50/50 p-5"><Badge variant="outline" className="rounded-full border-emerald-200 bg-white/70 text-emerald-700">{member.membership.status}</Badge><p className="mt-4 text-xl font-black text-slate-800">{member.membership.plan}</p><div className="mt-5 space-y-3 border-t border-emerald-100 pt-4 text-sm"><div className="flex justify-between gap-3"><span className="text-slate-400">Start</span><span className="font-semibold text-slate-700">{formatDate(member.membership.startDate)}</span></div><div className="flex justify-between gap-3"><span className="text-slate-400">End</span><span className="font-semibold text-slate-700">{formatDate(member.membership.endDate)}</span></div><div className="flex justify-between gap-3"><span className="text-slate-400">Amount</span><span className="font-black text-emerald-700">₹{member.membership.amount.toLocaleString("en-IN")}</span></div></div></div> : <div className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-cyan-200 bg-cyan-50/30 px-4 text-center"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-cyan-600 shadow-sm"><ShieldAlert className="h-5 w-5" /></div><p className="mt-3 text-sm font-bold text-slate-700">No membership yet</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-400">Assign a plan from Memberships when you are ready.</p></div>}</section>
    </div>
  </div>;
}
