import { NextResponse } from "next/server";
import { requireApiGymAdmin } from "@/lib/auth/api-guard";
import { getReceiptData } from "@/lib/data/payments";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function pdfText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function money(value: number): string {
  return `Rs. ${Math.round(value).toLocaleString("en-IN")}`;
}

function formatDate(value: Date | null): string {
  if (!value) return "—";
  return new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(new Date(value));
}

function buildPdf(data: NonNullable<Awaited<ReturnType<typeof getReceiptData>>>): Uint8Array {
  const commands: string[] = [];
  const text = (value: string, x: number, y: number, size = 11, bold = false) => {
    commands.push(`BT /${bold ? "F2" : "F1"} ${size} Tf ${x} ${y} Td (${pdfText(value)}) Tj ET`);
  };
  const line = (x1: number, y1: number, x2: number, y2: number) => {
    commands.push(`${x1} ${y1} m ${x2} ${y2} l S`);
  };

  commands.push("0.5 w");
  commands.push("50 50 495 742 re S");
  text(data.gym.name || "Fitaah", 70, 735, 22, true);
  text("PAYMENT RECEIPT", 70, 708, 13, true);
  text(`Receipt No: ${data.receiptNumber}`, 370, 735, 10, false);
  text(`Payment Date: ${formatDate(data.paymentDate)}`, 370, 718, 10, false);
  line(70, 695, 525, 695);

  text("MEMBER DETAILS", 70, 670, 10, true);
  text(`Name: ${data.member.name}`, 70, 650);
  text(`Mobile: ${data.member.phone || "—"}`, 70, 632);
  text(`Plan: ${data.planName}`, 70, 614);
  text(`Membership: ${formatDate(data.startDate)} - ${formatDate(data.endDate)}`, 70, 596);

  line(70, 575, 525, 575);
  text("PAYMENT DETAILS", 70, 550, 10, true);
  text("Membership Amount", 70, 525);
  text(money(data.membershipAmount), 400, 525, 11, true);
  text("Amount Paid", 70, 500);
  text(money(data.amountPaid), 400, 500, 11, true);
  text("Payment Method", 70, 475);
  text(data.method.replaceAll("_", " "), 400, 475, 11, true);
  text("Total Paid", 70, 450);
  text(money(data.totalPaid), 400, 450, 11, true);
  text("Outstanding", 70, 425);
  text(money(data.outstanding), 400, 425, 11, true);
  if (data.transactionReference) {
    text("Transaction Reference", 70, 400);
    text(data.transactionReference, 250, 400, 10);
  }

  line(70, 370, 525, 370);
  text(data.gym.address || "", 70, 345, 9);
  text(`Phone: ${data.gym.phone || "—"}`, 70, 328, 9);
  text(`Email: ${data.gym.email || "—"}`, 70, 311, 9);
  text("Thank you for your payment.", 70, 265, 12, true);
  text("Please keep this receipt for your records.", 70, 245, 9);
  text("Generated by Fitaah", 70, 75, 8);

  const stream = commands.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`;
  }
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new TextEncoder().encode(pdf);
}

export async function GET(
  _request: Request,
  { params }: { params: { paymentId: string } },
) {
  const auth = await requireApiGymAdmin();
  if (!auth.ok) return auth.response;

  const data = await getReceiptData(auth.user.gymId as string, params.paymentId);
  if (!data) return NextResponse.json({ error: "Payment not found" }, { status: 404 });

  const pdf = buildPdf(data);
  return new NextResponse(pdf as BodyInit, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${data.receiptNumber}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
