"use client";

import * as React from "react";
import { createPortal } from "react-dom";
import Link from "next/link";
import { CheckCircle2, ChevronLeft, ChevronRight, Eye, MoreHorizontal, Pencil, Plus, Search, Sparkles, UserRound, UserRoundX, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import type { MemberStatus } from "@/lib/constants";
import type { SerializedMember } from "@/lib/data/members";

interface MembersResponse { members: SerializedMember[]; total: number; page: number; pageSize: number; }
type Filter = "ALL" | MemberStatus;
type MenuPosition = { top: number; left: number };

function statusClass(status: MemberStatus): string { if (status === "ACTIVE") return "border-emerald-200 bg-emerald-50 text-emerald-700"; if (status === "FROZEN") return "border-amber-200 bg-amber-50 text-amber-700"; return "border-slate-200 bg-slate-50 text-slate-600"; }
function initials(name: string): string { return name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function formatDate(value: string, withYear = false): string { return new Intl.DateTimeFormat("en-IN", withYear ? { day: "numeric", month: "short", year: "numeric" } : { day: "numeric", month: "short" }).format(new Date(value)); }

export function MembersClient() {
  const [members, setMembers] = React.useState<SerializedMember[]>([]); const [total, setTotal] = React.useState(0); const [query, setQuery] = React.useState(""); const [status, setStatus] = React.useState<Filter>("ALL"); const [page, setPage] = React.useState(1); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [menuId, setMenuId] = React.useState<string | null>(null); const [menuPosition, setMenuPosition] = React.useState<MenuPosition | null>(null); const [updatingId, setUpdatingId] = React.useState<string | null>(null);

  const load = React.useCallback(async () => { setLoading(true); setError(null); try { const params = new URLSearchParams({ page: String(page), pageSize: "12" }); if (query.trim()) params.set("q", query.trim()); if (status !== "ALL") params.set("status", status); const response = await fetch(`/api/members?${params.toString()}`, { cache: "no-store" }); const data = (await response.json()) as MembersResponse & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Unable to load members"); setMembers(data.members); setTotal(data.total); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load members"); } finally { setLoading(false); } }, [page, query, status]);
  React.useEffect(() => { void load(); }, [load]);
  React.useEffect(() => { if (!menuId) return; const close = () => { setMenuId(null); setMenuPosition(null); }; window.addEventListener("scroll", close, true); window.addEventListener("resize", close); return () => { window.removeEventListener("scroll", close, true); window.removeEventListener("resize", close); }; }, [menuId]);

  function openMenu(event: React.MouseEvent<HTMLButtonElement>, id: string) { if (menuId === id) { setMenuId(null); setMenuPosition(null); return; } const rect = event.currentTarget.getBoundingClientRect(); const menuWidth = 190; const menuHeight = 150; const gap = 8; const left = Math.min(Math.max(8, rect.right - menuWidth), window.innerWidth - menuWidth - 8); const top = rect.bottom + menuHeight + gap <= window.innerHeight ? rect.bottom + gap : Math.max(8, rect.top - menuHeight - gap); setMenuId(id); setMenuPosition({ top, left }); }

  async function toggleStatus(member: SerializedMember) { const nextStatus: MemberStatus = member.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; setUpdatingId(member.id); try { const response = await fetch(`/api/members/${member.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus }) }); if (!response.ok) throw new Error("Unable to update member status"); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update member status"); } finally { setUpdatingId(null); setMenuId(null); setMenuPosition(null); } }

  const pages = Math.max(1, Math.ceil(total / 12)); const activeCount = members.filter((member) => member.status === "ACTIVE").length; const membershipCount = members.filter((member) => Boolean(member.membership)).length; const selectedMember = members.find((member) => member.id === menuId);

  return <div className="space-y-6 sm:space-y-7">
    <section className="relative overflow-hidden rounded-[1.75rem] border border-emerald-100 bg-gradient-to-br from-white via-emerald-50/70 to-cyan-50/70 p-5 shadow-[0_18px_50px_rgba(16,185,129,0.08)] sm:p-7 lg:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-emerald-300/20 blur-3xl" /><div className="absolute -bottom-24 right-1/3 h-48 w-48 rounded-full bg-cyan-300/20 blur-3xl" /><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/75 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-700"><Sparkles className="h-3.5 w-3.5" />Member management</div><h1 className="font-heading text-3xl font-black tracking-[-0.035em] text-slate-900 sm:text-4xl">Your members, beautifully organised.</h1><p className="mt-2.5 max-w-xl text-sm leading-6 text-slate-500">Find members quickly, see their membership at a glance, and keep your gym directory up to date.</p></div><Button asChild className="inline-flex h-11 w-full shrink-0 flex-row items-center justify-center gap-2 whitespace-nowrap rounded-xl bg-emerald-600 px-5 font-semibold text-white shadow-lg shadow-emerald-600/20 hover:bg-emerald-700 sm:w-auto"><Link href="/members/new" className="inline-flex items-center justify-center gap-2 whitespace-nowrap"><Plus className="h-4 w-4 shrink-0" />Add member</Link></Button></div><div className="relative mt-6 grid grid-cols-3 gap-2 sm:max-w-xl sm:gap-3">{[{ label: "Total members", value: total }, { label: "Active now", value: activeCount }, { label: "With membership", value: membershipCount }].map((item) => <div key={item.label} className="rounded-2xl border border-white/80 bg-white/75 p-3 backdrop-blur-sm sm:p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{item.label}</p><p className="mt-1 text-xl font-black text-slate-800 sm:text-2xl">{loading ? "—" : item.value}</p></div>)}</div></section>
    <Card className="rounded-[1.5rem] border-slate-200/80 bg-white shadow-[0_12px_40px_rgba(15,23,42,0.05)]"><div className="border-b border-slate-100 p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(e) => { setPage(1); setQuery(e.target.value); }} placeholder="Search name, phone or email..." className="h-11 rounded-xl border-slate-200 bg-slate-50/70 pl-10 pr-10 text-sm focus:border-emerald-300 focus:bg-white focus:ring-4 focus:ring-emerald-500/5" />{query ? <button type="button" onClick={() => { setPage(1); setQuery(""); }} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-700" aria-label="Clear search"><X className="h-4 w-4" /></button> : null}</div><div className="flex w-full overflow-x-auto rounded-xl bg-slate-100 p-1 lg:w-auto">{(["ALL", "ACTIVE", "FROZEN", "INACTIVE"] as Filter[]).map((item) => <button key={item} type="button" onClick={() => { setPage(1); setStatus(item); }} className={`shrink-0 rounded-lg px-3 py-2 text-xs font-semibold transition-all ${status === item ? "bg-white text-slate-800 shadow-sm" : "text-slate-400 hover:text-slate-700"}`}>{item === "ALL" ? "All" : item.charAt(0) + item.slice(1).toLowerCase()}</button>)}</div></div></div>
      {error ? <div className="m-4 flex items-center gap-2 rounded-xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700"><X className="h-4 w-4" />{error}</div> : null}
      {loading ? <div className="space-y-3 p-4 sm:p-5">{[1,2,3,4].map((item) => <div key={item} className="h-16 animate-pulse rounded-2xl bg-slate-100" />)}</div> : members.length === 0 ? <div className="flex min-h-80 flex-col items-center justify-center px-5 py-12 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-50 to-cyan-50 text-emerald-600"><UserRound className="h-7 w-7" /></div><h2 className="mt-4 font-heading text-xl font-bold text-slate-800">{query || status !== "ALL" ? "No members found" : "Start building your member base"}</h2><p className="mt-1 max-w-sm text-sm leading-6 text-slate-500">{query || status !== "ALL" ? "Try a different search or status filter." : "Add your first member and keep everything about their gym journey in one place."}</p>{!query && status === "ALL" ? <Button asChild className="mt-5 inline-flex flex-row items-center gap-2 rounded-xl bg-emerald-600 hover:bg-emerald-700"><Link href="/members/new" className="inline-flex items-center gap-2"><Plus className="h-4 w-4" />Add first member</Link></Button> : null}</div> : <>
        <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-slate-100 bg-slate-50/60"><th className="px-5 py-3.5 text-left text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">Member</th><th className="px-4 py-3.5 text-left text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">Contact</th><th className="px-4 py-3.5 text-left text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">Membership</th><th className="px-4 py-3.5 text-left text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">Status</th><th className="px-5 py-3.5 text-right text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400"> </th></tr></thead><tbody>{members.map((member) => <tr key={member.id} className="group border-b border-slate-100 last:border-0 transition-colors hover:bg-emerald-50/30"><td className="px-5 py-4"><Link href={`/members/${member.id}`} className="flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-100 to-cyan-100 text-xs font-black text-emerald-700">{initials(member.name)}</span><span className="min-w-0"><span className="block truncate font-semibold text-slate-800 group-hover:text-emerald-700">{member.name}</span><span className="mt-0.5 block text-xs text-slate-400">Joined {formatDate(member.joiningDate, true)}</span></span></Link></td><td className="px-4 py-4"><p className="font-medium text-slate-700">{member.phone}</p><p className="max-w-[220px] truncate text-xs text-slate-400">{member.email || "No email"}</p></td><td className="px-4 py-4">{member.membership ? <><p className="font-semibold text-slate-700">{member.membership.plan}</p><p className="mt-0.5 text-xs text-slate-400">Ends {formatDate(member.membership.endDate)}</p></> : <span className="text-xs text-slate-400">No membership assigned</span>}</td><td className="px-4 py-4"><Badge variant="outline" className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusClass(member.status)}`}>{member.status}</Badge></td><td className="px-5 py-4 text-right"><Button variant="ghost" size="icon-sm" className="rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label={`Actions for ${member.name}`} onClick={(event) => openMenu(event, member.id)}><MoreHorizontal className="h-4 w-4" /></Button></td></tr>)}</tbody></table></div>
        <div className="divide-y divide-slate-100 md:hidden">{members.map((member) => <div key={member.id} className="p-4"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-100 to-cyan-100 text-xs font-black text-emerald-700">{initials(member.name)}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><Link href={`/members/${member.id}`} className="font-semibold text-slate-800">{member.name}</Link><p className="mt-0.5 text-xs text-slate-400">{member.phone}</p></div><Badge variant="outline" className={`rounded-full text-[10px] ${statusClass(member.status)}`}>{member.status}</Badge></div><div className="mt-3 rounded-2xl border border-slate-100 bg-gradient-to-br from-slate-50 to-emerald-50/50 p-3.5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Membership</p><p className="mt-1 text-sm font-semibold text-slate-700">{member.membership?.plan ?? "No membership assigned"}</p></div>{member.membership ? <CheckCircle2 className="h-5 w-5 text-emerald-500" /> : null}</div>{member.membership ? <p className="mt-1 text-xs text-slate-400">Valid until {formatDate(member.membership.endDate, true)}</p> : null}</div><div className="mt-3 flex gap-2"><Button asChild variant="outline" size="sm" className="inline-flex h-9 flex-1 flex-row items-center justify-center gap-1.5 rounded-xl border-slate-200 whitespace-nowrap"><Link href={`/members/${member.id}`} className="inline-flex items-center gap-1.5 whitespace-nowrap"><Eye className="h-3.5 w-3.5" />View</Link></Button><Button asChild variant="outline" size="sm" className="inline-flex h-9 flex-1 flex-row items-center justify-center gap-1.5 rounded-xl border-slate-200 whitespace-nowrap"><Link href={`/members/${member.id}/edit`} className="inline-flex items-center gap-1.5 whitespace-nowrap"><Pencil className="h-3.5 w-3.5" />Edit</Link></Button><Button variant="outline" size="sm" className="inline-flex h-9 w-10 shrink-0 flex-row items-center justify-center rounded-xl border-slate-200 p-0" aria-label={`Actions for ${member.name}`} onClick={(event) => openMenu(event, member.id)}><MoreHorizontal className="h-4 w-4" /></Button></div></div></div></div>)}</div>
        <div className="flex flex-col gap-3 border-t border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-400">Showing {members.length} of {total} members</p><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((current) => current - 1)} className="inline-flex flex-row items-center gap-1.5 rounded-xl whitespace-nowrap"><ChevronLeft className="h-4 w-4" />Previous</Button><span className="flex h-9 min-w-9 items-center justify-center rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-600">{page} / {pages}</span><Button variant="outline" size="sm" disabled={page >= pages} onClick={() => setPage((current) => current + 1)} className="inline-flex flex-row items-center gap-1.5 rounded-xl whitespace-nowrap">Next<ChevronRight className="h-4 w-4" /></Button></div></div>
      </>}
    </Card>
    {selectedMember && menuPosition && typeof document !== "undefined" ? createPortal(<div className="fixed z-[100] w-[190px] rounded-2xl border border-slate-200 bg-white p-1.5 text-left shadow-2xl shadow-slate-900/15" style={{ top: menuPosition.top, left: menuPosition.left }} role="menu"><Link href={`/members/${selectedMember.id}`} onClick={() => { setMenuId(null); setMenuPosition(null); }} className="flex items-center gap-2.5 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-emerald-50 hover:text-emerald-700"><Eye className="h-4 w-4 text-emerald-600" />View profile</Link><Link href={`/members/${selectedMember.id}/edit`} onClick={() => { setMenuId(null); setMenuPosition(null); }} className="flex items-center gap-2.5 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-blue-50 hover:text-blue-700"><Pencil className="h-4 w-4 text-blue-500" />Edit member</Link><button type="button" disabled={updatingId === selectedMember.id} onClick={() => void toggleStatus(selectedMember)} className="flex w-full items-center gap-2.5 rounded-xl px-3 py-2.5 text-left text-sm font-medium text-rose-600 hover:bg-rose-50 disabled:opacity-50"><UserRoundX className="h-4 w-4" />{selectedMember.status === "ACTIVE" ? "Deactivate" : "Activate"}</button></div>, document.body) : null}
  </div>;
}
